export const SPECTRUM_COLORS = {
  BLACK: "#000000",
  BLUE: "#0100CE",
  RED: "#CF0100",
  MAGENTA: "#CF01CE",
  GREEN: "#00CF15",
  CYAN: "#01CFCF",
  YELLOW: "#CFCF15",
  WHITE: "#CFCFCF",
  BRIGHT_BLACK: "#000000",
  BRIGHT_BLUE: "#0200FD",
  BRIGHT_RED: "#FF0201",
  BRIGHT_MAGENTA: "#FF02FD",
  BRIGHT_GREEN: "#00FF1C",
  BRIGHT_CYAN: "#02FFFF",
  BRIGHT_YELLOW: "#FFFF1D",
  BRIGHT_WHITE: "#FFFFFF",
} as const;

export const SPECTRUM_WIDTH = 256;
export const SPECTRUM_HEIGHT = 192;
export const SPECTRUM_BORDER_WIDTH = 32;
export const SPECTRUM_BORDER_HEIGHT = 24;
export const SPECTRUM_TOTAL_WIDTH = SPECTRUM_WIDTH + SPECTRUM_BORDER_WIDTH * 2;
export const SPECTRUM_TOTAL_HEIGHT =
  SPECTRUM_HEIGHT + SPECTRUM_BORDER_HEIGHT * 2;
